//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakPortal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilanlar
    {
        public int ilanId { get; set; }
        public string ilanAdi { get; set; }
        public string ilanYer { get; set; }
        public int m2 { get; set; }
        public int fiyat { get; set; }
        public string ilanResim { get; set; }
    }
}
